### ISSUE TITLE
Udh ada casino belum  ? ini lawan orang lain bukan sama bot 

### ISSUE THREAD

**Issue by AlvioAdjiJanuar** [mrfzvx12/whatsapp-bot#7]

**Comment by AlvioAdjiJanuar** [comment]
Kalo belum ada , w kasih nih

**Comment by mrfzvx12** [comment]
Belum ada si...simpen aja dulu.. ini masih buat yang google asisten mu..

**Comment by mrfzvx12** [comment]
> > Belum ada si...simpen aja dulu.. ini masih buat yang google asisten mu..
> 
> emang belum selesai ? tpi bagus ga si fitur kek gitu hahaha

![IMG_20211111_221114](https://user-images.githubusercontent.com/72728486/141321754-6a75da8e-5ccb-4fe7-9fc7-6094b6eebf75.jpg)
Bagus banget malah.. kalo di ane mau buat itu command pake vn gini hasil akhirnya.. tinggal nambah" dikit doang si .

**Comment by AlvioAdjiJanuar** [comment]
Okee kalo bagus

**Comment by AlvioAdjiJanuar** [comment]
jangan lupa creditnya

**Comment by mrfzvx12** [comment]
> jangan lupa creditnya

Tentu saja.. masih bimbang.. mau open apa di enc biar gk gampang di colong..

**Comment by AlvioAdjiJanuar** [comment]
> > jangan lupa creditnya
> 
> Tentu saja.. masih bimbang.. mau open apa di enc biar gk gampang di colong..

di open aja

**Comment by mrfzvx12** [comment]
Baiklah.. close
